FROM python:3.10-slim

WORKDIR /app

COPY setup/resources/requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY app/ /app/

COPY setup/resources/entrypoint.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]

CMD ["gunicorn", "--config", "gunicorn.conf.py", "__init__:app"]
