version: '3.8'

services:
  app:
    build: .
    container_name: flask_app # Name of the app
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - .app:/app
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

  db:
    image: postgres:13
    container_name: postgres_db
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: redis_cache

volumes:
  pgdata:
